/** @type {import('tailwindcss').Config} */
import { fontFamily } from "tailwindcss/defaultTheme";

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/styles/**/*.{css}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#000000',
        secondary: '#1A1A1A',
        tertiary: '#2D2D2D',
        quaternary: '#0F0F0F',
        'accent-green': '#00FF85',
        'accent-green-hover': '#00FF41',
        'accent-red': '#FF4D4D',
        'accent-red-hover': '#FF3366',
        'accent-blue': '#00AAFF',
        'accent-blue-hover': '#0088FF',
        'accent-purple': '#FF00FF',
        'accent-purple-hover': '#CC00CC',
        'text-primary': '#FFFFFF',
        'text-secondary': '#B0B0B0',
        'text-muted': '#808080',
        'text-inverse': '#000000',
        'border-color': 'rgba(0, 255, 133, 0.2)',
        'border-hover': 'rgba(0, 255, 133, 0.4)',
        'bg-card': 'rgba(26, 26, 26, 0.8)',
        'bg-glass': 'rgba(0, 0, 0, 0.1)',
      },
      fontFamily: {
        heading: ['Montserrat', 'system-ui', 'sans-serif'],
        body: ['Roboto', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Consolas', 'monospace'],
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #000000 0%, #1A1A1A 50%, #000000 100%)',
        'gradient-secondary': 'linear-gradient(180deg, #1A1A1A 0%, #2D2D2D 50%, #1A1A1A 100%)',
        'gradient-accent-green': 'linear-gradient(135deg, #00FF85 0%, #00FF41 100%)',
        'gradient-accent-blue': 'linear-gradient(135deg, #00AAFF 0%, #0088FF 100%)',
        'gradient-glow-green': 'radial-gradient(circle at center, rgba(0, 255, 133, 0.3) 0%, transparent 70%)',
        'gradient-glow-blue': 'radial-gradient(circle at center, rgba(0, 170, 255, 0.3) 0%, transparent 70%)',
        'gradient-glow-purple': 'radial-gradient(circle at center, rgba(255, 0, 255, 0.3) 0%, transparent 70%)',
        'grid-pattern': 'linear-gradient(rgba(0, 255, 133, 0.1) 1px, transparent 1px), linear-gradient(rgba(0, 255, 133, 0.1) 1px, transparent 1px)',
      },
      boxShadow: {
        'glow-green': '0 0 20px rgba(0, 255, 133, 0.5)',
        'glow-blue': '0 0 20px rgba(0, 170, 255, 0.5)',
        'glow-purple': '0 0 20px rgba(255, 0, 255, 0.5)',
        'card': '0 4px 20px rgba(0, 0, 0, 0.3)',
        'inset': 'inset 0 2px 4px rgba(0, 0, 0, 0.5)',
      },
      spacing: {
        'xs': '0.25rem',
        'sm': '0.5rem',
        'md': '1rem',
        'lg': '1.5rem',
        'xl': '2rem',
        '2xl': '3rem',
      },
      borderRadius: {
        'sm': '0.25rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
      },
      animationDuration: {
        'fast': '150ms',
        'normal': '300ms',
        'slow': '500ms',
      },
      zIndex: {
        'dropdown': '1000',
        'sticky': '1020',
        'modal': '1030',
        'tooltip': '1040',
      },
      keyframes: {
        'float': 'float 4s ease-in-out infinite',
        'scanline': 'scanline 2s linear infinite',
        'spin': 'spin 1s linear infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'slide-up': 'slide-up 0.5s ease-out',
        'fade-in': 'fade-in 0.8s ease-out',
      },
      transform: {
        'translate-y-full': 'translateY(-100%)',
        'translate-y-0': 'translateY(0)',
        'translate-y-full-negative': 'translateY(-100%)',
        'translate-x-full': 'translateX(-100%)',
        'translate-x-0': 'translateX(0)',
        'translate-x-full': 'translateX(100%)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
  ],
}
